set -g mouse on
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "sainnhe/tmux-fzf"

# keybinds
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
TMUX_FZF_LAUNCH_KEY="C-f"

# init tmux plugin manager (must be at bottom)
run "~/.config/tmux/plugins/tpm/tpm"
